# 開発用 dockerfile.dev
FROM python:3.11-slim

WORKDIR /app

# インストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ソースコードをコピー
COPY app .

# 環境変数
ENV PYTHONUNBUFFERED=1

# デバッグ実行
CMD ["python", "app/main.py"]